MODEL:


TRAIN:
  train_data_dir: [
    '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/train1',
    '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/train2',
  ]
  batch_size: 512
  width: 128
  height: 32
  epochs: 500
  cuda: True
  ngpu: 1
  workers: 4
  resume: ''
  ckpt_dir: './ckpt/'
  voc_type: 'all' #'digits lower upper all'
  saveInterval: 200
  displayInterval: 100 #display loss
  adadelta: False
  lr: 0.001
  adam: True
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
      '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/test/hard',
      '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/test/easy',
      '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/test/medium',
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 200 #-1, val at the end of epoch
    rec_pretrained: '/home/p_pianigiani4/Tesi/tsrn/TSRN/recognizers/demo.pth.tar'
    moran_pretrained: '/home/p_pianigiani4/Tesi/tsrn/TSRN/recognizers/moran.pth'
    crnn_pretrained: '/home/p_pianigiani4/Tesi/tsrn/TSRN/recognizers/crnn.pth'

TEST:
  checkpoint: ''
  test_data_dir: [
      '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/test/hard',
      '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/test/easy',
      '/home/p_pianigiani4/Tesi/tsrn/TSRN/dataset/test/medium',
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
